language: node_js
node_js:
- '8'
after_success:
- npm run coverage
deploy:
  provider: npm
  email: toxictoxer@gmail.com
  on:
    tags: true
  api_key:
    secure: AQz/mKkY30OxRqpSONbdrR/es+m3JKv3Hc6vAK44RZ3y7h8At99KPhNikd2l5w1QtB7o365pgD6SK7ydt72R0kSSuIFnqgq2NenX+Dqh77/a7eSnVN5zJjtVxOQYW32iO8TCqfZNlxiW5Y55AM6JchITRy5yPl6drfMpSb8CuCUhZsd+oyMxiGeRNGsPoHR+gfnEBdjwFEm1D7kTjhQG4EY5vuFGgW2fzdftuBj+nUdC012smcUSBIhomaTp4KeZ1siAnIH1XntRDjUZt6w4VS946SpTMElC3CLSCeQOtgBwd4Te7UaYPeWTVotr6B1DzRX9rMe88dRuPvhH5V9R7yO0VZfasKgs2TAuK4g94nVM9P+Xg+9AjI0Q0WEQaG6BUOzzOZS9zfoWmP2jn1GHxF2RphhiXkR48YHlB9HIUEblpM3k/eztGaQ+xCnjgyw1vJJHZmaqJg6LYYd9ImlR/NXP9a0hMfgxQdW0JpWi4TmNwKltQAty3hRZMk2Qz58jTebEPYxHyuxRvnHm/1L5uku0dnCbQIcDKXkcdioGVYtLBXkzRmqADoUAOd2c6v3IOlCyrBiHgde4/0KwgDC8wR0ZNG1AUXzN/DvA3+ON5eBlj8E6KgmaBdIfIEJ0023hAMIUTde+aK3cYkwReQkYvHoXvdlhFq0d2VPM3PqKyK0=
